### ISSUE TITLE
BisiclesToGlimmer

### ISSUE THREAD

**Issue by JeremyEly** [CISM/cism#7]
Hello. 
I am trying to compile CISM with BISICLES using the linux-gnu-bisicles-cmake script.
Initially I get the error:
.... /BISICLES/BisiclesToGlimmer.H:16:25: error bike_driver.H: No such file or directory

If I change this line from bike_driver.H to BisiclesToGlimmer.H, I get further in the compile, but get the following errors related to bike_driver:

../BisiclesToGlimmer.cpp:29 error:'bike_driver_init' was not declared in this scope
../BisiclesToGlimmer.cpp:39 error:'bike_driver_run' was not declared in this scope
../BisiclesToGlimmer.cpp:46 error:'bike_driver_finalize' was not declared in this scope

Any help much appreciated.
Jeremy.

**Comment by whlipscomb** [comment]
Hello Jeremy

Assuming this had reached you, I am one of the bisicles developers,  and I
heard through a slightly complicated route that you were trying to build
the cism/bisicles code. The route you have tried is probably not going to
work because it relies on a non-free version of bisicles that is not
generally available.  However,  there is a route that does work and is
completely free.

Let me know if you are interested.

Stephen Cornford
